[wokwi]
version = 1
firmware = '.pio/build/esp32dev/firmware.bin'
elf = '.pio/build/esp32dev/firmware.elf'
# firmware = '.pio/build/lolin_s2_mini/firmware.'.pio/build/franzininho_wifi/firmware.elf'bin'
# elf = '.pio/build/lolin_s2_mini/firmware.elf'